export const LOGIN_FLOW = "LOGIN_FLOW";
export const LOGIN_FLOW_SUCCESS = "LOGIN_FLOW_SUCCESS";
export const LOGIN_FLOW_FAILED = "LOGIN_FLOW_FAILED";

export const SET_AUTH = "SET_AUTH";
export const LOGOUT = "LOGOUT";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
