export const FETCH_BIRTHDAY_BY_GIFT_COUNT = "FETCH_BIRTHDAY_BY_GIFT_COUNT";
export const FETCH_BIRTHDAY_BY_GIFT_COUNT_SUCCESS = "FETCH_BIRTHDAY_BY_GIFT_COUNT_SUCCESS";

export const FETCH_BIRTHDAY_BY_RECENT = "FETCH_BIRTHDAY_BY_RECENT";
export const FETCH_BIRTHDAY_BY_RECENT_SUCCESS = "FETCH_BIRTHDAY_BY_RECENT_SUCCESS";

export const FETCH_BIRTHDAY_BY_MONTH = "FETCH_BIRTHDAY_BY_MONTH";
export const FETCH_BIRTHDAY_BY_MONTH_SUCCESS = "FETCH_BIRTHDAY_BY_MONTH_SUCCESS";

export const FETCH_DONATE_LIST = "FETCH_DONATE_LIST";
export const FETCH_DONATE_LIST_SUCCESS = "FETCH_DONATE_LIST_SUCCESS";

export const FETCH_BIRTHDAY_CARD = "FETCH_BIRTHDAY_CARD";
export const FETCH_BIRTHDAY_CARD_SUCCESS = "FETCH_BIRTHDAY_CARD_SUCCESS";

export const FETCH_BIRTHDAY_GIFT_CATEGORY = "FETCH_BIRTHDAY_GIFT_CATEGORY";
export const FETCH_BIRTHDAY_GIFT_CATEGORY_SUCCESS = "FETCH_BIRTHDAY_GIFT_CATEGORY_SUCCESS";

export const DONATE_GIFT = "DONATE_GIFT";
export const DONATE_GIFT_SUCCESS = "DONATE_GIFT_SUCCESS";

export const SET_BIRTHDAY_PAGE = "SET_BIRTHDAY_PAGE";

export const SET_IS_LOAD_MORE = "SET_IS_LOAD_MORE";

export const GET_HOST = "GET_HOST";
export const GET_HOST_SUCCESS = "GET_HOST_SUCCESS";
