export const FETCH_REVENUE = "FETCH_REVENUE"
export const FETCH_REVENUE_SUCCESS = "FETCH_REVENUE_SUCCESS"
export const FETCH_REVENUE_FAILED = "FETCH_REVENUE_FAILED"

export const FETCH_RANKING = "FETCH_RANKING"
export const FETCH_RANKING_SUCCESS = "FETCH_RANKING_SUCCESS"
export const FETCH_RANKING_FAILED = "FETCH_RANKING_FAILED"
