export const FETCH_SHOP_LIST = 'FETCH_SHOP_LIST';
export const FETCH_SHOP_LIST_SUCCESS = 'FETCH_SHOP_LIST_SUCCESS';
export const FETCH_SHOP_LIST_FAILED = 'FETCH_SHOP_LIST_FAILED';

export const GET_ONE_SHOP_LIST = 'GET_ONE_SHOP_LIST';
export const GET_ONE_SHOP_LIST_SUCCESS = 'GET_ONE_SHOP_LIST_SUCCESS';
export const GET_ONE_SHOP_LIST_FAILED = 'GET_ONE_SHOP_LIST_FAILED';

export const UPLOAD_AVATAR_SHOP_SUCCESS = 'UPLOAD_AVATAR_SHOP_SUCCESS';

export const UPDATE_SHOP_ITEM = 'UPDATE_SHOP_ITEM';
export const UPDATE_SHOP_ITEM_SUCCESS = 'UPDATE_SHOP_ITEM_SUCCESS';
export const UPDATE_SHOP_ITEM_FAILED = 'UPDATE_SHOP_ITEM_FAILED';

export const CREATE_SHOP_ITEM = 'CREATE_SHOP_ITEM';
export const CREATE_SHOP_ITEM_SUCCESS = 'CREATE_SHOP_ITEM_SUCCESS';
export const CREATE_SHOP_ITEM_FAILED = 'CREATE_SHOP_ITEM_FAILED';

export const DELETE_SHOP_ITEM = 'DELETE_SHOP_ITEM';
export const DELETE_SHOP_ITEM_SUCCESS = 'DELETE_SHOP_ITEM_SUCCESS';
export const DELETE_SHOP_ITEM_FAILED = 'DELETE_SHOP_ITEM_FAILED';

export const ACTIVE_STATUS = 'ACTIVE_STATUS';
export const ACTIVE_STATUS_SUCCESS = 'ACTIVE_STATUS_SUCCESS';
export const ACTIVE_STATUS_FAILED = 'ACTIVE_STATUS_FAILED';
