export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILED = 'UPLOAD_AVATAR_FAILED';

export const DELETE_TEMP_IMAGE = 'DELETE_TEMP_IMAGE';
export const DELETE_TEMP_IMAGE_SUCCESS = 'DELETE_TEMP_IMAGE_SUCCESS';

export const UPLOAD_GALLERY_HOST = 'UPLOAD_GALLERY_HOST';
export const UPLOAD_GALLERY_HOST_SUCCESS = 'UPLOAD_GALLERY_HOST_SUCCESS';
export const UPLOAD_GALLERY_HOST_FAILED = 'UPLOAD_GALLERY_HOST_FAILED';

export const UPLOAD_GALLERY_HOST_TEMP_SUCCESS = 'UPLOAD_GALLERY_HOST_TEMP_SUCCESS';
export const UPLOAD_AVATAR_SHOP_SUCCESS = 'UPLOAD_AVATAR_SHOP_SUCCESS';

export const UPLOAD_AVATAR_USER_SUCCESS = 'UPLOAD_AVATAR_USER_SUCCESS';
