export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED';

export const FETCH_GALLERY_HOST = 'FETCH_GALLERY_HOST';
export const FETCH_GALLERY_HOST_SUCCESS = 'FETCH_GALLERY_HOST_SUCCESS';
export const FETCH_GALLERY_HOST_FAILED = 'FETCH_GALLERY_HOST_FAILED';

export const DELETE_GALLERY_ITEM_HOST = 'DELETE_GALLERY_ITEM_HOST';
export const DELETE_GALLERY_ITEM_HOST_SUCCESS = 'DELETE_GALLERY_ITEM_HOST_SUCCESS';
export const DELETE_GALLERY_ITEM_HOST_FAILED = 'DELETE_GALLERY_ITEM_HOST_FAILED';

export const FETCH_HOST_SALES = 'FETCH_HOST_SALES';
export const FETCH_HOST_SALES_SUCCESS = 'FETCH_HOST_SALES_SUCCESS';
export const FETCH_HOST_SALES_FAILED = 'FETCH_HOST_SALES_FAILED';

export const ACTIVE_USER_REGISTER = 'ACTIVE_USER_REGISTER';
export const ACTIVE_USER_REGISTER_SUCCESS = 'ACTIVE_USER_REGISTER_SUCCESS';
export const ACTIVE_USER_REGISTER_FAILED = 'ACTIVE_USER_REGISTER_FAILED';

export const RESEND_ACTIVE_USER = 'RESEND_ACTIVE_USER';
export const RESEND_ACTIVE_USER_SUCCESS = 'RESEND_ACTIVE_USER_SUCCESS';
export const RESEND_ACTIVE_USER_FAILED = 'RESEND_ACTIVE_USER_FAILED';

export const REMOVE_IMAGE_AVATAR_USER = 'REMOVE_IMAGE_AVATAR_USER';
export const REMOVE_IMAGE_AVATAR_USER_SUCCESS = 'REMOVE_IMAGE_AVATAR_USER_SUCCESS';
export const REMOVE_IMAGE_AVATAR_USER_FAILED = 'REMOVE_IMAGE_AVATAR_USER_FAILED';
